### ISSUE TITLE
Bookmark/Home Screen shortcut blank

### ISSUE THREAD

**Issue by muhelen** [mmmewk/crosswordle#16] opened 2022-03-08 11:03 UTC
@mmmewk Hi, I've noticed your recent build caused blank screen on my existing iOS shortcut. I need to re-save to play again. Kindly check. Thanks.

**Comment by mmmewk** [comment] 2022-03-09 07:08
Hmm, I can't reproduce this. Hard to say whats going on without steps to reproduce... Probably something with old stale data being persisted into state.

**Comment by mmmewk** [comment] 2022-03-14 07:53
Should be fixed now, can you confirm?

**Comment by muhelen** [comment] 2022-03-14 11:44
Hi, I can't reproduce the error again as I've updated a new bookmark earlier. Hope someone else can verify on this. Thanks.

**Comment by mmmewk** [comment] 2022-03-16 07:13
I added an error page that notifies the user to write a bug report, so I'm going to close this for now until someone brings it back up

**Closed by mmmewk** 2022-03-16 07:13 UTC

**Comment by muhelen** [comment] 2022-03-16 08:57
Okay great 👍
